DDCE-5031 Initial changes for play 3.0 migrations
hmrc/binding-tariff-filestore pull request #64
Opened 2024-03-20 12:45 UTC by mywyau

2024-03-21 13:56 UTC, EdCope requested changes

2024-03-21 13:56 UTC, EdCope commented on project/AppDependencies.scala
> +    "org.apache.httpcomponents"     % "httpmime"                  % apacheHttpVersion,
Like Scalaj we agreed to remove other http clients. This one seems to be only used in one test

2024-03-28 09:00 UTC, EdCope requested changes

2024-03-28 10:06 UTC, mywyau commented on project/CodeCoverageSettings.scala
> +    "<empty>",
<img width="1671" alt="Screenshot 2024-03-28 at 10 06 01" src="https://github.com/hmrc/binding-tariff-filestore/assets/47248104/2c939a09-b753-4ada-b109-24c14919959c">

2024-03-28 10:08 UTC, Taiwo-AB commented on project/CodeCoverageSettings.scala
> +    "<empty>",
If you want to take out empty then you should use `coverageExcludedFiles := ".*Routes.*"` and delete the val.

2024-03-28 10:13 UTC, EdCope commented on project/CodeCoverageSettings.scala
> +    "<empty>",
Sorry, i didn't realise it was doing this to `FileStoreController`. What Taiwo said is an option or can leave then

2024-03-28 10:40 UTC, mywyau commented on it/test/resources/upscan/initiate_response.json
think this has been cleaned up now, deleted some files and removed the ResourceFiles trait

2024-03-28 10:41 UTC, mywyau commented on project/CodeCoverageSettings.scala
> +    "<empty>",
no worries kept checking it and leaving it in and forgot to leave a message my bad.

2024-03-28 10:43 UTC, mywyau commented on project/AppDependencies.scala
> +    "org.apache.httpcomponents"     % "httpmime"                  % apacheHttpVersion,
I think we should leave it as extra work and make a new ticket. No idea on what the rewrite would look like. And should just get the migration over first.

2024-04-04 15:31 UTC, EdCope approved these changes

2024-04-04 15:33 UTC, merged